### ISSUE TITLE
Compile Error in latest package

### ISSUE THREAD

**Issue by RedIronLabs** [breadnone/STween#2]
Thank you for this project, I just wanted to mention in the latest version that the following command:

`TweenLoop.TweenPlayerLoop.tweenLoop.UnregisterUpdate();`

No longer exists, and will generate two errors in the project.  One that `tweenLoop` isn't public, and the other is that `UnregisterUpdate` doesn't exist.  I've assumed that both of these are no longer needed though and just commented it out on my side.  

Just wanted to let you know

**Comment by breadnone** [comment]
will look into it today, thanks!

**Comment by breadnone** [comment]
Fixed in latest main and release!  Closing

**Comment by breadnone** [comment]
@RedIronLabs  note, Make sure to clear the existing installer/package due to new folder layout
