### ISSUE TITLE
Can't Build with this in a Project (Editor scripts)

### ISSUE THREAD

**Issue by RedIronLabs** [breadnone/STween#3]
Hello,

Just another mention, when you try to build a project, you may see an error about:  `The type or namespace name 'Editor' could not be found...` or variation therein.

This is because the testing library's aren't under an `#if UNITY_EDITOR` to block out the editor script.  Just a heads up

**Comment by breadnone** [comment]
Edit : I built the latest it's fine on my end.  Could you point out which script that causing it?

**Comment by breadnone** [comment]
Fixed in latest main and release!  Closing

**Comment by breadnone** [comment]
@RedIronLabs  note, Make sure to clear the existing installer/package due to new folder layout
